var resources = {
	basePath:"assets/",
	manifest:[
		{src:"images/Grass.png", id:"Grass"},
		{src:"images/p1.png", id:"p1"},
		{src:"images/p2.png", id:"p2"},
		{src:"images/p3.png", id:"p3"},
		{src:"images/p4.png", id:"p4"},
		{src:"images/p5.png", id:"p5"},
		{src:"images/p6.png", id:"p6"},
		{src:"images/p7.png", id:"p7"},
		{src:"images/b1.png", id:"b1"},
		{src:"images/b2.png", id:"b2"},
		{src:"images/b3.png", id:"b3"},
		{src:"images/b4.png", id:"b4"},
		{src:"images/b5.png", id:"b5"},
		{src:"images/b6.png", id:"b6"},
		{src:"images/b7.png", id:"b7"},
		{src:"images/b8.png", id:"b8"},
		{src:"images/b9.png", id:"b9"},
		{src:"images/o1.png", id:"o1"},
		{src:"images/o2.png", id:"o2"},
		{src:"images/o3.png", id:"o3"},
		{src:"images/o4.png", id:"o4"},
		{src:"images/o5.png", id:"o5"},
		{src:"images/o6.png", id:"o6"},
		{src:"images/o7.png", id:"o7"},
		{src:"images/o8.png", id:"o8"},
		{src:"images/o9.png", id:"o9"},
		{src:"images/r1.png", id:"r1"},
		{src:"images/r2.png", id:"r2"},
		{src:"images/r3.png", id:"r3"},
		{src:"images/r4.png", id:"r4"},
		{src:"images/r5.png", id:"r5"},
		{src:"images/r6.png", id:"r6"},
		{src:"images/r7.png", id:"r7"},
		{src:"images/r8.png", id:"r8"},
		{src:"images/r9.png", id:"r9"},
		
		{src:"../../common/images/pauseIconC.png", id:"pauseIconC"},
		{src:"../../common/images/pauseIconO.png", id:"pauseIconO"},
		{src:"../../common/images/pauseIconN.png", id:"pauseIconN"},
		
		{src:"../../common/images/playIconC.png", id:"playIconC"},
		{src:"../../common/images/playIconO.png", id:"playIconO"},
		{src:"../../common/images/playIconN.png", id:"playIconN"},
		
		{src:"../../common/images/replayIconC.png", id:"replayIconC"},
		{src:"../../common/images/replayIconO.png", id:"replayIconO"},
		{src:"../../common/images/replayIconN.png", id:"replayIconN"},
		
		{src:"../../common/images/decD.png", id:"decD"},
		{src:"../../common/images/decN.png", id:"decN"},
		{src:"../../common/images/decO.png", id:"decO"},
		
		{src:"../../common/images/incD.png", id:"incD"},
		{src:"../../common/images/incN.png", id:"incN"},
		{src:"../../common/images/incO.png", id:"incO"},
	]
}