var layout = {
	background:[
		
	],
	foreground:[{
			name:"bg",
			namespace:"lib",
			type:"mc_bg",
			transform:[569.3,417.8,1,1,0,0,0,971.3,628.4]
		},{
			name:"patch",
			namespace:"lib",
			type:"Symbol8",
			transform:[512,758.8]
		},{
			name:"helicopter",
			namespace:"lib",
			type:"mc_Helicoptercopy",
			transform:[190,420,1.20,1.20,0,0,0,53.5,49.6],
		},{
			name:"helicopterBreak",
			namespace:"lib",
			type:"mc_Helicopter",
			transform:[190,420,1.20,1.20,0,0,0,53.5,49.6],
		},{
			name:"v_velocity",
			namespace:"createjs",
			type:"Text",
			props:{
				x:64,
				y:743,
				font:"bold 16px Arial",
				color:"white",
				text:"0.00",
				textAlign:"center"
			}
		},{
			name:"v_acceleration",
			type:"Text",
			namespace:"createjs",
			props:{
				x:65,
				y:777,
				font:"bold 16px Arial",
				color:"white",
				text:"0.00",
				textAlign:"center"
			}
		},{
			name:"h_velocity",
			namespace:"createjs",
			type:"Text",
			props:{
				x:189,
				y:743,
				font:"bold 16px Arial",
				color:"white",
				text:"0.00",
				textAlign:"center"
			}
		},{
			name:"h_acceleration",
			type:"Text",
			namespace:"createjs",
			props:{
				x:189,
				y:777,
				font:"bold 16px Arial",
				color:"white",
				text:"0.00",
				textAlign:"center"
			}
		},{
			name:"force",
			namespace:"createjs",
			type:"Text",
			props:{
				x:724,
				y:750,
				font:"bold 18px Arial",
				color:"black",
				text:"0",
				textAlign:"center"
			}
		},{
			name:"liftForce",
			namespace:"createjs",
			type:"Text",
			props:{
				x:442,
				y:750,
				font:"bold 18px Arial",
				color:"black",
				text:"0",
				textAlign:"center"
			}
		},{
			name:"pauseButton",
			type:"Button",
			up:"pauseIconN",
			over:"pauseIconO",
			down:"pauseIconC",
			props:{
				x:870,
				y:724,
				scaleX:0.5 * 1.25,
				scaleY:0.5 * 1.25,
			}
		},{
			name:"playButton",
			type:"Button",
			up:"playIconN",
			over:"playIconO",
			down:"playIconC",
			props:{
				x:870,
				y:724,
				scaleX:0.5 * 1.25,
				scaleY:0.5 * 1.25,
			}
		},{
			name:"resetButton",
			type:"Button",
			up:"replayIconN",
			over:"replayIconO",
			down:"replayIconC",
			props:{
				x:943,
				y:724,
				scaleX:0.5 * 1.25,
				scaleY:0.5 * 1.25,
			}
		},{
			name:"stepperH",
			type:"NumericStepper",
			value:0,
			min:-5000,
			max:5000,
			step:250,
			inc:{
				up:"incNH",
				over:"incOH",
				down:"incDH",
			},
			dec:{
				up:"decNH",
				over:"decOH",
				down:"decDH",
			},
			gap:1,
			props:{
				x:639,
				y:737,
				scaleX:0.6,
				scaleY:0.6,
			}
		},{
			name:"stepperV",
			type:"NumericStepper",
			value:0,
			min:-200000,
			max:50000,
			step:250,
			inc:{
				up:"incNV",
				over:"incOV",
				down:"incDV",
			},
			dec:{
				up:"decNV",
				over:"decOV",
				down:"decDV",
			},
			gap:1,
			props:{
				x:349,
				y:721,
				scaleX:0.6,
				scaleY:0.6,
			}
		},
	]
}