var layout = {
	background:[{
		name:"bg",
		namespace:"lib",
		type:"mc_bg",
		transform:[569.3,417.8,1,1,0,0,0,971.3,628.4]
	},{
			name:"patch",
			namespace:"lib",
			type:"Symbol8",
			transform:[512,758.8]
	},{
			name:"velocityUnit",
			namespace:"createjs",
			type:"Text",
			props:{
				x:425,
				y:742,
				font:"bold 18px Arial",
				color:"white",
				text:"m/s",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"velocityText",
			namespace:"createjs",
			type:"Text",
			props:{
				x:318,
				y:742,
				font:"bold italic 18px Arial",
				color:"white",
				text:"v",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"direction",
			namespace:"createjs",
			type:"Text",
			props:{
				x:268,
				y:760,
				font:"bold 18px Arial",
				color:"white",
				text:"Vertical",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"accelrationUnit",
			namespace:"createjs",
			type:"Text",
			props:{
				x:425,
				y:777,
				font:"bold 18px Arial",
				color:"white",
				text:"m/s",
				textAlign:"center",
				textBaseline:"middle"
			},
		},{
			name:"accelrationUnitS",
			namespace:"createjs",
			type:"Text",
			props:{
				x:445,
				y:773,
				font:"bold 12px Arial",
				color:"white",
				text:"2",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"acclerationText",
			namespace:"createjs",
			type:"Text",
			props:{
				x:318,
				y:777,
				font:"bold italic 18px Arial",
				color:"white",
				text:"a",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"heightText",
			namespace:"createjs",
			type:"Text",
			props:{
				x:67,
				y:759,
				font:"bold 18px Arial",
				color:"white",
				text:"Height",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"heightUnit",
			namespace:"createjs",
			type:"Text",
			props:{
				x:195,
				y:759,
				font:"bold 18px Arial",
				color:"white",
				text:"m",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"forceUnit",
			namespace:"createjs",
			type:"Text",
			props:{
				x:717,
				y:759,
				font:"bold 18px Arial",
				color:"white",
				text:"N",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"forceText",
			namespace:"createjs",
			type:"Text",
			props:{
				x:510,
				y:759,
				font:"bold 18px Arial",
				color:"white",
				text:"Net Force",
				textAlign:"center",
				textBaseline:"middle"
			}
		},
	],
	foreground:[
		{
			name:"helicopter",
			namespace:"lib",
			type:"mc_Helicoptercopy",
			//transform:[290,420,1.5,1.5,0,0,0,53.5,49.6],
		},{
			name:"helicopterBreak",
			namespace:"lib",
			type:"mc_Helicopter",
			transform:[290,420,1.5,1.5,0,0,0,53.5,49.6],
		},{
			name:"popup",
			namespace:"lib",
			type:"popup",
			transform:[235.4,707.3,1,1,0,0,0,-8.1,15.3],
		},{
			name:"velocity",
			namespace:"createjs",
			type:"Text",
			props:{
				x:368,
				y:744,
				font:"bold 16px Arial",
				color:"White",
				text:"0.00",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"accleration",
			type:"Text",
			namespace:"createjs",
			props:{
				x:368,
				y:779,
				font:"bold 16px Arial",
				color:"White",
				text:"0.00",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"height",
			namespace:"createjs",
			type:"Text",
			props:{
				x:144,
				y:761,
				font:"bold 16px Arial",
				color:"White",
				text:"0.00",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"force",
			namespace:"createjs",
			type:"Text",
			props:{
				x:657,
				y:761,
				font:"bold 19px Arial",
				color:"black",
				text:"0",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"resetButton",
			type:"Button",
			up:"replayIconN",
			over:"replayIconO",
			down:"replayIconC",
			props:{
				x:938,
				y:728,
				scaleX:0.5 * 1.25,
				scaleY:0.5 * 1.25,
			}
		},{
			name:"stepper",
			type:"NumericStepper",
			value:0,
			min:-200000,
			max:30000,
			step:250,
			inc:{
				up:"incN",
				over:"incO",
				down:"incD",
			},
			dec:{
				up:"decN",
				over:"decO",
				down:"decD",
			},
			gap:1,
			props:{
				x:562,
				y:723,
				scaleX:0.6,
				scaleY:0.6,
			}
		},
	]
}