var layout = {
	background:[{
		name:"bg",
		namespace:"lib",
		type:"Bg",
		transform:[521.6,414.6,1,1,0,0,0,548.1,439.1]
	},
	{
		name:"patch",
		namespace:"lib",
		type:"Button_Set_1",
		transform:[512,758.8]
	},{
			name:"velocityUnit",
			namespace:"createjs",
			type:"Text",
			props:{
				x:225,
				y:741,
				font:"bold 18px Arial",
				color:"white",
				text:"m/s",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"velocityText",
			namespace:"createjs",
			type:"Text",
			props:{
				x:122,
				y:741,
				font:"bold italic 18px Arial",
				color:"white",
				text:"v",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"direction",
			namespace:"createjs",
			type:"Text",
			props:{
				x:70,
				y:760,
				font:"bold 18px Arial",
				color:"white",
				text:"Vertical",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"accelrationUnit",
			namespace:"createjs",
			type:"Text",
			props:{
				x:225,
				y:777,
				font:"bold 18px Arial",
				color:"white",
				text:"m/s",
				textAlign:"center",
				textBaseline:"middle"
			},
		},{
			name:"accelrationUnitS",
			namespace:"createjs",
			type:"Text",
			props:{
				x:247,
				y:774,
				font:"bold 12px Arial",
				color:"white",
				text:"2",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"acclerationText",
			namespace:"createjs",
			type:"Text",
			props:{
				x:122,
				y:777,
				font:"bold italic 18px Arial",
				color:"white",
				text:"a",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"forceUnit",
			namespace:"createjs",
			type:"Text",
			props:{
				x:522,
				y:760,
				font:"bold 18px Arial",
				color:"white",
				text:"N",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"forceText",
			namespace:"createjs",
			type:"Text",
			props:{
				x:316,
				y:760,
				font:"bold 18px Arial",
				color:"white",
				text:"Lift Force",
				textAlign:"center",
				textBaseline:"middle"
			}
		},
		
	],
	foreground:[
		{
			name:"peoplesSuccess",
			namespace:"lib",
			type:"Cherecter2",
			transform:[490.1,453.8],
		},{
			name:"peoplesBreak",
			namespace:"lib",
			type:"Cherecter1",
			transform:[490.1,453.8],
		},{
			name:"peoplesNormal",
			namespace:"lib",
			type:"Cherecter3",
			transform:[490.1,453.8],
		},{
			name:"helicopter",
			namespace:"lib",
			type:"mc_Helicoptercopy",
			transform:[540,170,1.25,1.25,0,0,0,53.5,49.6],
		},{
			name:"helicopterBreak",
			namespace:"lib",
			type:"mc_Helicopter",
			transform:[540,501,1.25,1.25,0,0,0,53.5,49.6],
		},{
			name:"velocity",
			namespace:"createjs",
			type:"Text",
			props:{
				x:171,
				y:743,
				font:"bold 16px Arial",
				color:"white",
				text:"0.00",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"accleration",
			type:"Text",
			namespace:"createjs",
			props:{
				x:171,
				y:779,
				font:"bold 16px Arial",
				color:"white",
				text:"0.00",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"force",
			namespace:"createjs",
			type:"Text",
			props:{
				x:461,
				y:760,
				font:"bold 18px Arial",
				color:"black",
				text:"0",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"pauseButton",
			type:"Button",
			up:"pauseIconN",
			over:"pauseIconO",
			down:"pauseIconC",
			props:{
				x:865,
				y:728,
				scaleX:0.5 * 1.25,
				scaleY:0.5 * 1.25,
			}
		},{
			name:"playButton",
			type:"Button",
			up:"playIconN",
			over:"playIconO",
			down:"playIconC",
			props:{
				x:865,
				y:728,
				scaleX:0.5 * 1.25,
				scaleY:0.5 * 1.25,
			}
		},{
			name:"resetButton",
			type:"Button",
			up:"replayIconN",
			over:"replayIconO",
			down:"replayIconC",
			props:{
				x:938,
				y:728,
				scaleX:0.5 * 1.25,
				scaleY:0.5 * 1.25,
			}
		},{
			name:"stepper",
			type:"NumericStepper",
			value:0,
			min:0,
			max:40000,
			step:250,
			inc:{
				up:"incN",
				over:"incO",
				down:"incD",
			},
			dec:{
				up:"decN",
				over:"decO",
				down:"decD",
			},
			gap:1,
			props:{
				x:367,
				y:723,
				scaleX:0.6,
				scaleY:0.6,
			}
		},
	]
}