var layout = {
	background:[
		
	],
	foreground:[{
			name:"bg",
			namespace:"createjs",
			type:"Bitmap",
			img:"bg",
			props:{
				// regX:971.3
			},
			cache:{x:0, y:0, width:5000, height:2000, scale:2}
			// transform:[569.3,417.8,1,1,0,0,0,971.3,628.4]
		},{
			name:"patch",
			namespace:"lib",
			type:"Symbol8",
			transform:[512,758.8],
		},{
			name:"v_velocityUnit",
			namespace:"createjs",
			type:"Text",
			props:{
				x:214,
				y:741,
				font:"bold 18px Arial",
				color:"white",
				text:"m/s",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"v_velocityText",
			namespace:"createjs",
			type:"Text",
			props:{
				x:120,
				y:741,
				font:"bold italic 18px Arial",
				color:"white",
				text:"v",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"v_direction",
			namespace:"createjs",
			type:"Text",
			props:{
				x:75,
				y:759,
				font:"bold 18px Arial",
				color:"white",
				text:"Vertical",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"v_accelrationUnit",
			type:"Text",
			namespace:"createjs",
			props:{
				x:214,
				y:777,
				font:"bold 18px Arial",
				color:"white",
				text:"m/s",
				textAlign:"center",
				textBaseline:"middle"
			},
		},{
			name:"v_accelrationUnitS",
			type:"Text",
			namespace:"createjs",
			props:{
				x:235,
				y:774,
				font:"bold 12px Arial",
				color:"white",
				text:"2",
				textAlign:"center",
				textBaseline:"middle"
			},
		},{
			name:"v_acclerationText",
			namespace:"createjs",
			type:"Text",
			props:{
				x:120,
				y:777,
				font:"bold italic 18px Arial",
				color:"white",
				text:"a",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"h_velocityUnit",
			namespace:"createjs",
			type:"Text",
			props:{
				x:472,
				y:741,
				font:"bold 18px Arial",
				color:"white",
				text:"m/s",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"h_velocityText",
			namespace:"createjs",
			type:"Text",
			props:{
				x:375,
				y:741,
				font:"bold italic 18px Arial",
				color:"white",
				text:"v",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"h_direction",
			namespace:"createjs",
			type:"Text",
			props:{
				x:315,
				y:758,
				font:"bold 18px Arial",
				color:"white",
				text:"Horizontal",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"h_accelrationUnit",
			namespace:"createjs",
			type:"Text",
			props:{
				x:472,
				y:777,
				font:"bold 18px Arial",
				color:"white",
				text:"m/s",
				textAlign:"center",
				textBaseline:"middle"
			},
		},
		{
			name:"h_accelrationUnitS",
			namespace:"createjs",
			type:"Text",
			props:{
				x:494,
				y:774,
				font:"bold 12px Arial",
				color:"white",
				text:"2",
				textAlign:"center",
				textBaseline:"middle"
			},
		},{
			name:"h_acclerationText",
			namespace:"createjs",
			type:"Text",
			props:{
				x:375,
				y:777,
				font:"bold italic 18px Arial",
				color:"white",
				text:"a",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"forceUnit",
			namespace:"createjs",
			type:"Text",
			props:{
				x:797,
				y:759,
				font:"bold 18px Arial",
				color:"white",
				text:"N",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"forceText",
			namespace:"createjs",
			type:"Text",
			props:{
				x:550,
				y:750,
				font:"bold 18px Arial",
				color:"white",
				text:"Thrust Force",
				textAlign:"center",
				lineWidth:6,
				lineHeight:21,
				textBaseline:"middle"
			}
		},{
			name:"helicopter",
			namespace:"lib",
			type:"mc_Helicoptercopy",
			transform:[310.8,370.5,1.736,1.736,0,0,0,53.5,49.6],
		},{
			name:"helicopterBreak",
			namespace:"lib",
			type:"mc_Helicopter",
			transform:[589.5,373.2,1.736,1.736,0,0,0,53.5,49.6],
		},{
			name:"h_velocity",
			namespace:"createjs",
			type:"Text",
			props:{
				x:417,
				y:743,
				font:"bold 16px Arial",
				color:"white",
				text:"0.00",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"h_accleration",
			type:"Text",
			namespace:"createjs",
			props:{
				x:417,
				y:779,
				font:"bold 16px Arial",
				color:"white",
				text:"0.00",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"v_velocity",
			namespace:"createjs",
			type:"Text",
			props:{
				x:163,
				y:743,
				font:"bold 16px Arial",
				color:"white",
				text:"0.00",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"v_accleration",
			type:"Text",
			namespace:"createjs",
			props:{
				x:163,
				y:779,
				font:"bold 16px Arial",
				color:"white",
				text:"0.00",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"force",
			namespace:"createjs",
			type:"Text",
			props:{
				x:739,
				y:761,
				font:"bold 18px Arial",
				color:"black",
				text:"0",
				textAlign:"center",
				textBaseline:"middle"
			}
		},{
			name:"pauseButton",
			type:"Button",
			up:"pauseIconN",
			over:"pauseIconO",
			down:"pauseIconC",
			props:{
				x:865,
				y:728,
				scaleX:0.5 * 1.25,
				scaleY:0.5 * 1.25,
			}
		},{
			name:"playButton",
			type:"Button",
			up:"playIconN",
			over:"playIconO",
			down:"playIconC",
			props:{
				x:865,
				y:728,
				scaleX:0.5 * 1.25,
				scaleY:0.5 * 1.25,
			}
		},{
			name:"resetButton",
			type:"Button",
			up:"replayIconN",
			over:"replayIconO",
			down:"replayIconC",
			props:{
				x:938,
				y:728,
				scaleX:0.5 * 1.25,
				scaleY:0.5 * 1.25,
			}
		},{
			name:"stepper",
			type:"NumericStepper",
			value:0,
			min:-5000,
			max:5000,
			step:250,
			inc:{
				up:"incN",
				over:"incO",
				down:"incD",
			},
			dec:{
				up:"decN",
				over:"decO",
				down:"decD",
			},
			gap:1,
			props:{
				x:642,
				y:739,
				scaleX:0.73,
				scaleY:0.6,
			}
		},
	]
}