var layout = {
	background:[
		{
			name:"bg",
			namespace:"lib",
			type:"mc_bg",
			transform:[512.1,265.5,1,1,0,0,0,512.3,266.3]
		},
		{
			name:"patch",
			namespace:"lib",
			type:"Symbol3copy4",
			transform:[511.6,722.6]
		}
	],
	foreground:[	
		{
			name:"textv1",
			namespace:"createjs",
			type:"Text",
			props:{
				x:158,
				y:665,
				font:"bold 18px Arial",
				text:"200",
				color:"white",
				textAlign:"center"
			}
		},
		{
			name:"textv2",
			namespace:"createjs",
			type:"Text",
			props:{
				x:158,
				y:697,
				font:"bold 18px Arial",
				text:"200",
				color:"white",
				textAlign:"center"
			}
		},
		{
			name:"textv3",
			namespace:"createjs",
			type:"Text",
			props:{
				x:158,
				y:729,
				font:"bold 18px Arial",
				text:"200",
				color:"white",
				textAlign:"center"
			}
		},
		{
			name:"textv4",
			namespace:"createjs",
			type:"Text",
			props:{
				x:158,
				y:761,
				font:"bold 18px Arial",
				text:"200",
				color:"white",
				textAlign:"center"
			}
		},
		{
			name:"textv5",
			namespace:"createjs",
			type:"Text",
			props:{
				x:375,
				y:665,
				font:"bold 18px Arial",
				text:"200",
				color:"white",
				textAlign:"center"
			}
		},
		{
			name:"textv6",
			namespace:"createjs",
			type:"Text",
			props:{
				x:375,
				y:697,
				font:"bold 18px Arial",
				text:"200",
				color:"white",
				textAlign:"center"
			}
		},
		{
			name:"textv7",
			namespace:"createjs",
			type:"Text",
			props:{
				x:375,
				y:729,
				font:"bold 18px Arial",
				text:"200",
				color:"white",
				textAlign:"center"
			}
		},
		{
			name:"textv8",
			namespace:"createjs",
			type:"Text",
			props:{
				x:375,
				y:761,
				font:"bold 18px Arial",
				text:"200",
				color:"white",
				textAlign:"center"
			}
		},
		{
			name:"LableTextv1",
			namespace:"createjs",
			type:"Text",
			props:{
				x:78,
				y:665,
				font:"bold 18px Arial",
				text:"Molecule 1:",
				color:"white",
				textAlign:"center"
			}
		},
		{
			name:"LableTextv2",
			namespace:"createjs",
			type:"Text",
			props:{
				x:78,
				y:697,
				font:"bold 18px Arial",
				text:"Molecule 2:",
				color:"white",
				textAlign:"center"
			}
		},
		{
			name:"LableTextv3",
			namespace:"createjs",
			type:"Text",
			props:{
				x:78,
				y:729,
				font:"bold 18px Arial",
				text:"Molecule 3:",
				color:"white",
				textAlign:"center"
			}
		},
		{
			name:"LableTextv4",
			namespace:"createjs",
			type:"Text",
			props:{
				x:78,
				y:761,
				font:"bold 18px Arial",
				text:"Molecule 4:",
				color:"white",
				textAlign:"center"
			}
		},
		{
			name:"LableTextv5",
			namespace:"createjs",
			type:"Text",
			props:{
				x:295,
				y:665,
				font:"bold 18px Arial",
				text:"Molecule 5:",
				color:"white",
				textAlign:"center"
			}
		},
		{
			name:"LableTextv6",
			namespace:"createjs",
			type:"Text",
			props:{
				x:295,
				y:697,
				font:"bold 18px Arial",
				text:"Molecule 6:",
				color:"white",
				textAlign:"center"
			}
		},
		{
			name:"LableTextv7",
			namespace:"createjs",
			type:"Text",
			props:{
				x:295,
				y:729,
				font:"bold 18px Arial",
				text:"Molecule 7:",
				color:"white",
				textAlign:"center"
			}
		},
		{
			name:"LableTextv8",
			namespace:"createjs",
			type:"Text",
			props:{
				x:295,
				y:761,
				font:"bold 18px Arial",
				text:"Molecule 8:",
				color:"white",
				textAlign:"center"
			}
		},
		{
			name:"unitTextv1",
			namespace:"createjs",
			type:"Text",
			props:{
				x:204,
				y:665,
				font:"bold 18px Arial",
				text:"m/s",
				color:"white",
				textAlign:"center"
			}
		},
		{
			name:"unitTextv2",
			namespace:"createjs",
			type:"Text",
			props:{
				x:204,
				y:697,
				font:"bold 18px Arial",
				text:"m/s",
				color:"white",
				textAlign:"center"
			}
		},
		{
			name:"unitTextv3",
			namespace:"createjs",
			type:"Text",
			props:{
				x:204,
				y:729,
				font:"bold 18px Arial",
				text:"m/s",
				color:"white",
				textAlign:"center"
			}
		},
		{
			name:"unitTextv4",
			namespace:"createjs",
			type:"Text",
			props:{
				x:204,
				y:761,
				font:"bold 18px Arial",
				text:"m/s",
				color:"white",
				textAlign:"center"
			}
		},
		{
			name:"unitTextv5",
			namespace:"createjs",
			type:"Text",
			props:{
				x:423,
				y:665,
				font:"bold 18px Arial",
				text:"m/s",
				color:"white",
				textAlign:"center"
			}
		},
		{
			name:"unitTextv6",
			namespace:"createjs",
			type:"Text",
			props:{
				x:423,
				y:697,
				font:"bold 18px Arial",
				text:"m/s",
				color:"white",
				textAlign:"center"
			}
		},
		{
			name:"unitTextv7",
			namespace:"createjs",
			type:"Text",
			props:{
				x:423,
				y:729,
				font:"bold 18px Arial",
				text:"m/s",
				color:"white",
				textAlign:"center"
			}
		},
		{
			name:"unitTextv8",
			namespace:"createjs",
			type:"Text",
			props:{
				x:423,
				y:761,
				font:"bold 18px Arial",
				text:"m/s",
				color:"white",
				textAlign:"center"
			}
		},
		{
			name:"molecule1",
			namespace:"lib",
			type:"mc_redBall",
			props:{
				regX:21.5,
				regY:21.5,
			},
			cache:{x:0, y:0, width:50, height:50}
		},{
			name:"resetButton",
			type:"Button",
			up:"replayIconN",
			over:"replayIconO",
			down:"replayIconC",
			props:{
				x:940,
				y:693,
				scaleX:0.6,
				scaleY:0.6,
			}
		},{
			name:"pauseButton",
			type:"Button",
			up:"pauseIconN",
			over:"pauseIconO",
			down:"pauseIconC",
			props:{
				x:866,
				y:693,
				scaleX:0.6,
				scaleY:0.6,
			}
		},{
			name:"playButton",
			type:"Button",
			up:"playIconN",
			over:"playIconO",
			down:"playIconC",
			props:{
				x:866,
				y:693,
				scaleX:0.6,
				scaleY:0.6,
				visible:false
			}
		}
	]
}